#!/usr/bin/env bash
# packet manager
# 
# packet manager for scripts and software made in bash

# Version
# Current: 0.2-a5-rev3

# TODO for 0.2-a5-rev4
# Done!

# TODO
# - install function
#	.I have to choose between hosting a private server to have all the scripts in
#	.a remote folder or it gets tricky
# - delete function
#	.See above
# - update function (needs improvement)
#	.Currently the only way I can update the packet manage is via git
# - search function (has to work both online and locally)
#	.To GET the list of files from a github an API must be used and there is daily
#	.limit unless a client_id is used. I might have to host it in a private server.
# EOT

#################################################################################
# server address
declare -g server=''
# current version
declare -g current_version=0.2-a5-rev3
# Script path
declare -g local_path=$(dirname "$0")
# Server url
declare -g server='https://raw.githubusercontent.com/0ero1ne/null/master/null'

# Libraries
source $local_path/lib/0x00.sh

# Output version
printf "\n${Yellow}%12s${NC} [${Blue}%s${NC}]\n\n" ".null" "$current_version"
#printf "\t${NC}[${Blue}%s${NC}]\n\n" 

#################################################################################
# argument parser
[ $# -eq 0 ] && null_usage;
while getopts "ls:i:u" opt; do
	case $opt in
		l) null_list ;;			# List of all installed scripts
		s) null_search ;;		# Search function (local only)
		i) null_info ;;			# Retrieve info from a script (local only for now)
		u) null_update ;;		# Update function (works only for null)
		h | *) null_usage ;; 	# If no arguments print help
	esac
done

# EOF